name: Clone, Decrypt, and Push Entire Repo

on:
  workflow_dispatch:

jobs:
  clone-decrypt-push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout current repo
      - uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Decrypt all .sh files in current repo
      - name: Decrypt all .sh files
        run: python3 decrypt_all.py

      # 4️⃣ Clone target repo
      - name: Clone target repository
        env:
          GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/NuhaHumaira/aia.git target_repo

      # 5️⃣ Copy all files (entire current repo) to target repo
      - name: Copy all files to target repo
        run: |
          rsync -av --exclude=".git" ./ target_repo/

      # 6️⃣ Commit and push to target repo
      - name: Commit and push to target repo
        working-directory: target_repo
        env:
          GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Add decrypted repo files"
          git push origin main
